[project]
name = "obfuscidian"
version = "1.0.0.dev0"
description = "Obfuscate and encrypt your Obsidian vault to create secure and private backups."
readme = "README.md"
authors = [
    { name = "Jeff Shurtliff", email = "jeff@shurt.us" }
]
maintainers = [
    { name = "Jeff Shurtliff", email = "jeff@shurt.us" }
]
license = "Apache-2.0"
license-files = ["LICENSE"]
requires-python = ">=3.10"
classifiers = []
dependencies = [
    "click"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://github.com/jeffshurtliff/obfuscidian"
Changelog = "https://github.com/jeffshurtliff/obfuscidian/releases"
Issues = "https://github.com/jeffshurtliff/obfuscidian/issues"
CI = "https://github.com/jeffshurtliff/obfuscidian/actions"

[project.scripts]
obfuscidian = "obfuscidian.cli:cli"

[project.optional-dependencies]
test = ["pytest"]
